[package]
name = "esp_iot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
apex1_common = { path = "../apexsky/apex1_common", features = ["native"]}
buttplug_client = "10.0.2"
buttplug_core = "10.0.2"
buttplug_transport_websocket_tungstenite = "10.0.2"
chrono = "0.4.44"
futures = "0.3.32"
prost = "0.14.3"
rand = "0.10.1"
tokio = { version = "1.52.1", features = ["full"] }
tonic = { version = "0.14.5", features = ["zstd"] }
tonic-prost = "0.14.5"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["json", "chrono", "env-filter"] }
tracing-appender = "0.2.5"
