[package]
name = "ohosky_kmbox"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
embedded-graphics = "0.8.1"
obfstr = "0.4.4"
once_cell = "1.20.2"
rand = "0.9.0"
serial2-tokio = { version = "0.1.14", features = ["unix", "windows"] }
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["net", "io-util", "time"] }
tracing = "0.1.41"
zerocopy = { version = "0.8.16", features = ["derive", "simd-nightly"] }
