[package]
name = "apexsky_overlay"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
apex1_common = { path = "../apex1_common", default-features = false, optional = true }
async-trait = "0.1.89"
bevy = { version = "0.18.1", features = ["wayland"] }
bevy_async_task = "0.12.0"
bevy_egui = "0.39.1"
bevy_health_bar3d = "3.10.0"
chrono = "0.4.44"
#console-subscriber = "0.4.0"
homedir = { version = "0.3.6", optional = true }
fyrox-sound = "1.0.1"
rand = "0.10.1"
indexmap = "2.14.0"
instant = "0.1.13"
ndarray = "0.17.2"
obfstr = "0.4.4"
once_cell = "1.21.4"
parking_lot = { version = "0.12.5", features = ["nightly"] }
prost = "0.14.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
thiserror = "2.0.18"
tokio = { version = "1.52.1", features = ["rt", "macros"] }
tonic = { version = "0.14.5", default-features = false, features = [
    "codegen",
] }
tonic-prost = "0.14.5"
tonic-web-wasm-client = { version = "0.9.1", optional = true }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
    "json",
    "chrono",
    "env-filter",
] }
tracing-appender = { version = "0.2.5", optional = true }
tracing-web = { version = "0.1.3", optional = true }
url = "2.5.8"
wasm-bindgen-futures = { version = "0.4.70", optional = true }
web-sys = { version = "0.3.97", optional = true, features = [
    "Document",
    "Location",
    "Screen",
    "UrlSearchParams",
    "Window",
] }
ron = "0.12.1"

[target.'cfg(unix)'.dependencies]
uzers = "0.12.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.4.2", default-features = false, features = ["wasm_js"] }
# Fix for `fyrox`: force "js" feature on getrandom 0.2 (via rand 0.8) to support wasm32-unknown-unknown.
getrandom_old = { package = "getrandom", default-features = false, version = "=0.2", features = ["js"] }

[build-dependencies]
tonic-prost-build = "0.14.5"

[features]
default = ["native"]
native = ["homedir", "tokio/full", "tonic/transport", "tonic/zstd", "tracing-appender"]
web-wasm = [
    "tonic-web-wasm-client",
    "tracing-web",
    "instant/wasm-bindgen",
    "wasm-bindgen-futures",
    "web-sys",
]
web-wasm-webgpu = ["web-wasm", "bevy/webgpu"]
web-wasm-webgl = ["web-wasm", "bevy/webgl2"]
apex1-inspect = ["apex1_common"]
