use super::Skyapex;

#[skyapex_impl]
pub trait OffsetsLoader {
    fn export_offsets(&mut self);
    fn offset_entitylist(&mut self) -> i64;
    fn offset_local_ent(&mut self) -> i64;
    fn offset_name_list(&mut self) -> i64;
    fn offset_global_vars(&mut self) -> i64;
    fn offset_levelname(&mut self) -> i64;
    fn offset_clientstate(&mut self) -> i64;
    fn offset_signonstate(&mut self) -> i64;
    fn offset_host_map(&mut self) -> i64;
    fn offset_entity_team(&mut self) -> i64;
    fn offset_player_health(&mut self) -> i64;
    fn offset_entity_shield(&mut self) -> i64;
    fn offset_entity_maxshield(&mut self) -> i64;
    fn offset_player_helmettype(&mut self) -> i64;
    fn offset_player_armortype(&mut self) -> i64;
    fn offset_entiry_name(&mut self) -> i64;
    fn offset_entity_sign_name(&mut self) -> i64;
    fn offset_centity_abs_velocity(&mut self) -> i64;
    fn offset_visible_time(&mut self) -> i64;
    fn offset_player_zooming(&mut self) -> i64;
    fn offset_traversal_progress(&mut self) -> i64;
    fn offset_traversal_starttime(&mut self) -> i64;
    fn offset_platform_uid(&mut self) -> i64;
    fn offset_weapon_name(&mut self) -> i64;
    fn offset_off_weapon(&mut self) -> i64;
    fn offset_wall_run_start_time(&mut self) -> i64;
    fn offset_wall_run_clear_time(&mut self) -> i64;
    fn offset_centity_flags(&mut self) -> i64;
    fn offset_in_attack(&mut self) -> i64;
    fn offset_in_toggle_duck(&mut self) -> i64;
    fn offset_in_zoom(&mut self) -> i64;
    fn offset_in_forward(&mut self) -> i64;
    fn offset_in_jump(&mut self) -> i64;
    fn offset_in_duck(&mut self) -> i64;
    fn offset_in_use(&mut self) -> i64;
    fn offset_player_life_state(&mut self) -> i64;
    fn offset_bleed_out_state(&mut self) -> i64;
    fn offset_centity_viewoffset(&mut self) -> i64;
    fn offset_centity_origin(&mut self) -> i64;
    fn offset_bones(&mut self) -> i64;
    fn offset_studiohdr(&mut self) -> i64;
    fn offset_cplayer_aimpunch(&mut self) -> i64;
    fn offset_cplayer_camerapos(&mut self) -> i64;
    fn offset_player_viewangles(&mut self) -> i64;
    fn offset_breath_angles(&mut self) -> i64;
    fn offset_observer_mode(&mut self) -> i64;
    fn offset_ovserver_target(&mut self) -> i64;
    fn offset_matrix(&mut self) -> i64;
    fn offset_render(&mut self) -> i64;
    fn offset_primary_weapon(&mut self) -> i64;
    fn offset_active_weapon(&mut self) -> i64;
    fn offset_bullet_speed(&mut self) -> i64;
    fn offset_bullet_scale(&mut self) -> i64;
    fn offset_weaponx_zoom_fov(&mut self) -> i64;
    fn offset_weaponx_ammo_in_clip(&mut self) -> i64;
    fn offset_centity_modelname(&mut self) -> i64;
    fn offset_cplayer_timebase(&mut self) -> i64;
    fn offset_cplayer_viewmodels(&mut self) -> i64;
    fn offset_crosshair_last(&mut self) -> i64;
    fn offset_input_system(&mut self) -> i64;
    fn offset_weaponx_bitfield_from_player(&mut self) -> i64;
    fn offset_entity_highlight_generic_context(&mut self) -> i64;
}
